on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: deploy
        - name: Merge from trunk
          run: git merge trunk
        - name: Run tests
          run: npm run zips
        - name: Update deploy branch
          run: git add -A && git commit -m "update deploy branch" && git push origin deploy